nama = input ("Nama :")
nim = input ("NIM :")
Kelas = input ("Kelas Pararel :")
alamat = input ("Alamat :") 
hobi = input ("Hobi :")
hp = input ("No. Hp :")

print("Nama :", nama)
print ("NIM :", nim)
print("Kelas Pararel :", Kelas)
print("Alamat :",alamat)
print("Hobi :", hobi)
print("No. HP :", hp)