print("################################")
print("#                              #")
print("#  Muhammad Naufal Abdillah    #")
print("#        2410817310007         #")
print("#                              #")
print("################################")