Nomor = int(input("Masukan angka:"))
if Nomor >= 100: print("Anda melebihi limit bilangan")
elif Nomor == 0: print("Nol")
elif Nomor == 10: print("Puluhan")
elif  11<= Nomor <=19: print("Belasan")
elif 20<= Nomor <= 99: print("puluhan")
else: print("Satuan")